### ISSUE TITLE
Should support extended Tweets

### ISSUE THREAD

**Issue by andypiper** [this-week-in/twitter-pinboard-cleanup-job#1]
https://github.com/this-week-in/twitter-pinboard-cleanup-job/blob/22ce58bdae57810db68a46854ff60dc3c153de08/src/main/kotlin/com/joshlong/twitter/api/BaseTwitterClient.kt#L25

In order to get the full text for extended ( >140 char) Tweets, you’ll want to use `tweet_mode=extended` here. Mind you, that complicates thing as then you’ll also want to use the `full_text` field instead of `text`. Might be helpful, though.

Note that the data formats will change a lot in the next version of the API (currently known as Twitter Developer Labs) - there’s no timeline endpoint available there yet, so it’s probably not worth worrying about right now, just some information for you.

**Comment by joshlong** [comment]
Wow! thanks so much. I'll incorporate that change now.
